version: '3'

services:
  master:
    extra_hosts:
      - "host.docker.internal:host-gateway"
    image: locust-hsfs:master
    ports:
     - "8089:8089"
    volumes:
      - ./:/home/locust
    command: -f /home/locust/locustfile.py MySQLFeatureVectorLookup --master --headless --expect-workers 1 -u 1 -r 1 -t 10 -s 1 --html=/home/locust/result-docker.html

  worker:
    extra_hosts:
      - "host.docker.internal:host-gateway"
    image: locust-hsfs:master
    volumes:
      - ./:/home/locust
    command: -f /home/locust/locustfile.py MySQLFeatureVectorLookup --worker --master-host master
